# Generated by Django 4.1.3 on 2022-11-25 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='check_worker_duty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workerid', models.PositiveIntegerField()),
                ('workername', models.CharField(max_length=20)),
                ('dutyvalue', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl', models.PositiveIntegerField()),
                ('lat', models.FloatField(max_length=20)),
                ('lon', models.FloatField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='details_house',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('housename', models.CharField(max_length=20)),
                ('lat', models.FloatField(max_length=20)),
                ('lon', models.FloatField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='nearby_bins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl', models.PositiveIntegerField()),
                ('lat', models.FloatField(max_length=20)),
                ('lon', models.FloatField(max_length=20)),
                ('value', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='pickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('workerid', models.PositiveIntegerField()),
                ('pi_date', models.DateField()),
                ('pi_time', models.TimeField()),
                ('lat', models.FloatField(max_length=20)),
                ('lon', models.FloatField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='user_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('full_name', models.CharField(max_length=20)),
                ('phone', models.PositiveIntegerField()),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='worker_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workerid', models.CharField(max_length=20)),
                ('full_name', models.CharField(max_length=20)),
                ('phone', models.PositiveIntegerField()),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
