# Generated by Django 4.1.3 on 2022-11-30 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0002_userdetails_delete_check_worker_duty_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='passwor2',
            new_name='password2',
        ),
    ]
