# Generated by Django 4.1.3 on 2022-12-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0004_userdetails_typeuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('lon', models.DecimalField(decimal_places=8, max_digits=10)),
                ('lat', models.DecimalField(decimal_places=8, max_digits=10)),
                ('img', models.ImageField(upload_to='')),
                ('desc', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ManageBins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binid', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('capacity', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ManageHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('houseid', models.CharField(max_length=50)),
                ('lon', models.DecimalField(decimal_places=8, max_digits=10)),
                ('lat', models.DecimalField(decimal_places=8, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='pickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('lat', models.DecimalField(decimal_places=8, max_digits=10)),
                ('lon', models.DecimalField(decimal_places=8, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='TrackTruck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck', models.PositiveIntegerField()),
                ('lon', models.DecimalField(decimal_places=8, max_digits=10)),
                ('lat', models.DecimalField(decimal_places=8, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='TrackWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('lon', models.DecimalField(decimal_places=8, max_digits=10)),
                ('lat', models.DecimalField(decimal_places=8, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('number', models.PositiveIntegerField()),
                ('password', models.CharField(max_length=50)),
                ('password2', models.CharField(max_length=50)),
                ('typeuser', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='email',
            field=models.CharField(max_length=150),
        ),
    ]
