# Generated by Django 4.1.3 on 2022-12-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0005_complaint_managebins_managehouse_pickup_tracktruck_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='managebins',
            name='lat',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='managebins',
            name='lon',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=10),
        ),
    ]
