# Generated by Django 4.1.3 on 2022-12-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0007_pickup_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('lon', models.DecimalField(decimal_places=8, max_digits=10)),
                ('lat', models.DecimalField(decimal_places=8, max_digits=10)),
                ('address', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='')),
                ('complaint', models.TextField(max_length=250)),
                ('tags', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='complaint',
        ),
    ]
